### ISSUE TITLE
undefined function

### ISSUE THREAD

**Issue by hamzak11111** [atisharma/chasm_engine#13]
https://github.com/atisharma/chasm_engine/blob/d58a4e743fe676232a7638d4b88495e2bcd02e03/chasm_engine/place.hy#L87

Where is place-json defined?

**Comment by atisharma** [comment]
https://github.com/atisharma/chasm_engine/blob/d58a4e743fe676232a7638d4b88495e2bcd02e03/chasm_engine/place.hy#L30

The macro `def-fill-template` defines it.
https://github.com/atisharma/chasm_engine/blob/d58a4e743fe676232a7638d4b88495e2bcd02e03/chasm_engine/instructions.hy#L63
