### ISSUE TITLE
How do I start the server?

### ISSUE THREAD

**Issue by gavinblair** [atisharma/chasm_engine#2]
I'm not sure what to do after configuring the world.

**Comment by gavinblair** [comment]
I found this on [reddit](https://www.reddit.com/r/LocalLLaMA/comments/16oa9dw/comment/k1lrxct/?utm_source=share&utm_medium=web2x&context=3):
1.  Install anaconda
2. Install oobabooga textgen (which is it's own can of worms)
3. Download the chasm_engine and chasm repositories from github and unzip them.
4. Open anaconda (Windows key, search for "anaconda")
5. Go to your chasm folder 
    cd /your/folder/to/chasm/
6. Create a new conda environment and activate it
    conda create --name chasm
    conda activate chasm
7. Install the requirements
    pip install -r chasm-main/requirements.txt
    pip install -r chasm_engine-main/requirements.txt
8. Remove ".example" from the file name in chasm_engine-main/server.toml.example
9. Open the file, put # in front of every line from 26-29 (to disable OpenAI and only use it locally), save it.
10. Remove ".example" from the file name in chasm-main/server.toml.example
11. Open the file and replace the "passphrase = " line with "passphrase = "asdf"" (It doesn't work without a passphrase?)
12. Start oobabooga, there go to "Session", check "openai" and then click "Apply flags/extensions and restart"
13. Open an anaconda console (see 4.) and run
    conda activate chasm
    python3 -m chasm_engine
    (That's the server. It will start generating the world. This can take looong.)
14. Open another anaconda console (see 4. harder) and run
    conda activate chasm
    python3 -m chasm

**Comment by atisharma** [comment]
I added some installation instructions. Hopefully enough to get people going.
