### ISSUE TITLE
/help is calling the LLM

### ISSUE THREAD

**Issue by kadogo** [atisharma/chasm_engine#5]
Hello @atisharma 

I noticed that when I called /help command, it was calling the LLM. Is there any reason for that?

I didn't really read the full code yet because I don't know `hy` so I will read about it later.
If there is no reason to use the LLM if /help is called, I think it would be better to parse it before.
I don't know whether it's straightforward to do or not, when I understand `hy` a bit better, I will maybe give it a try.

Cheers

**Comment by atisharma** [comment]
Yeah, it probably doesn't need to. In `engine.hy` function `parse`, the repl loop calls the world development which involves behind-the scenes calls to LLMs. Perhaps it could be skipped.

**Comment by atisharma** [comment]
It's not directly calling the LLM. What's happening is that the background thread is developing the world (spawning items, characters etc). There's a lot of this in a new world and it can take a long while to settle down.

**Comment by kadogo** [comment]
Hello,
So the best way would to have a way that calling direct commands are not blocking by the world generation?
I don't know if it's something that is achievable with the actual implementation.

**Comment by kadogo** [comment]
Alright, so even if it doesn't use the LLM for the /help command, it is still needed to have one other API server available.

I will give it a try when I have a bit of time, thanks.
